### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by agoosev** [caarlos0/duration#1]
Hi @caarlos0,

Thank you for your work!
Could you please add the LICENSE.md to this repository?

**Comment by caarlos0** [comment]
its on the file https://github.com/caarlos0/duration/blob/5d492514f3c7bf9654dbf6ee132896685d6ccb4b/duration.go#L1

**Comment by agoosev** [comment]
Thank you for your fast response!

Yes, but below there is a reference to the LICENSE file that does not exist: https://github.com/caarlos0/duration/blob/5d492514f3c7bf9654dbf6ee132896685d6ccb4b/duration.go#L3

Maybe it makes sense to add a reference to the Go source code license.  E.g.
```
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the [Golang repository](https://github.com/golang/go/blob/master/LICENSE).
```
What do you think?

**Comment by caarlos0** [comment]
yeah, sounds good I think

**Comment by agoosev** [comment]
I've created [PR](https://github.com/caarlos0/duration/pull/2). Could you take a look when you have time, please?
